---
title: "laud_samples"
author: "Lincoln"
date: "4/23/2019"
output: html_document
---

load libraries
```{r}
library(MutationalPatterns)
library(BSgenome)
```

load hg38
```{r}
ref_genome <- "BSgenome.Hsapiens.UCSC.hg38"
library(ref_genome, character.only = TRUE)
```

list some sample vcfs
```{r}
vcf_files <- list.files(path = './laud_samples', pattern = ".vcf", full.names = TRUE)
```

```{r}
cell_names <- stringr::str_remove_all(vcf_files, ".vcf")
cell_names <- stringr::str_remove_all(cell_names, "./laud_samples/")
```

load vcfs, as Grange objs
```{r}
vcfs <- read_vcfs_as_granges(vcf_files, cell_names, ref_genome, group = 'all')
summary(vcfs)
```

test test test
```{r}
for (i in 1:length(vcf_files)) {
  currFile = vcf_files[[i]]
  currCell = cell_names[[i]]
  print(currCell)
  read_vcfs_as_granges(currFile, currCell, ref_genome, group = 'all')
}
```

guess this creates a list of vcfs
```{r}
vcfs[[1]]
vcfs[[2]]
```

get base substitution rates, for single vcf 
```{r}
muts = mutations_from_vcf(vcfs[[1]])
head(muts, 12)
```

retrieve sequence context
```{r}
context = mut_context(vcfs[[3]], ref_genome)
head(context)
```

type context?
```{r}
type_context = type_context(vcfs[[1]], ref_genome)
lapply(type_context, head, 12)
```

get type of each mut
```{r}
type_occurrences <- mut_type_occurrences(vcfs, ref_genome)
type_occurrences
```

plot
```{r}
#pdf("test1.pdf", width=4, height=4)
p1 <- plot_spectrum(type_occurrences)
p1
#dev.off()
```

